name: ToggleInventory
main: com.github.yukinoraru.ToggleInventory.ToggleInventory
version: 1.3.0
dev-url: http://dev.bukkit.org/server-mods/toggleinventory/
author: yukinoraru
description: toggle inventory command.
api-version: "1.17"
commands:
  togglei:
    description: toggle inventory
    aliases: [ti]
    usage: |
      /<command> [0-n]
      Example: /<command> - toggle inventory like a ring
      Example: /<command> 1 - toggle inventory index 1
      Example: /it 1 - toggle inventory (reverse)
      Advanced: /ti [enable|disable|e|d] gamemode
      Advanced: /ti enable gamemode - enable with gamemode
  toggleir:
    description: toggle inventory (reverse)
    aliases: [it]
  toggleis:
    description: toggle inventory for special inventories
    aliases: [tis]
    usage: |
      /<command> [name]
      /<command> [add|delete] [name]
      /<command> [add-default|delete-default] [name]
      /<command> reset [-f]
      /<command> reset-default [-f]
      /<command> copy [name] [inventory index]
  toggleisr:
    description: toggle inventory for special inventories (reverse)
    aliases: [its]

permissions:
  toggle_inventory.toggle:
    default: op
    description: gives permission to /togglei command

  toggle_inventory.toggle_special:
    default: op
    description: gives permission to /toggleis command

  toggle_inventory.2:
    default: false
    description: max amounts of inventories is 2
  toggle_inventory.3:
    default: false
    description: max amounts of inventories is 3
  toggle_inventory.4:
    default: false
    description: max amounts of inventories is 4
  toggle_inventory.5:
    default: false
    description: max amounts of inventories is 5
  toggle_inventory.6:
    default: false
    description: max amounts of inventories is 6
  toggle_inventory.7:
    default: false
    description: max amounts of inventories is 7
  toggle_inventory.8:
    default: false
    description: max amounts of inventories is 8
  toggle_inventory.9:
    default: false
    description: max amounts of inventories is 9
  toggle_inventory.10:
    default: false
    description: max amounts of inventories is 10
  toggle_inventory.11:
    default: false
    description: max amounts of inventories is 11
  toggle_inventory.12:
    default: false
    description: max amounts of inventories is 12
  toggle_inventory.13:
    default: false
    description: max amounts of inventories is 13
  toggle_inventory.14:
    default: false
    description: max amounts of inventories is 14
  toggle_inventory.15:
    default: false
    description: max amounts of inventories is 15
  toggle_inventory.16:
    default: false
    description: max amounts of inventories is 16
  toggle_inventory.17:
    default: false
    description: max amounts of inventories is 17
  toggle_inventory.18:
    default: false
    description: max amounts of inventories is 18
  toggle_inventory.19:
    default: false
    description: max amounts of inventories is 19
  toggle_inventory.20:
    default: false
    description: max amounts of inventories is 20
  toggle_inventory.21:
    default: false
    description: max amounts of inventories is 21
  toggle_inventory.22:
    default: false
    description: max amounts of inventories is 22
  toggle_inventory.23:
    default: false
    description: max amounts of inventories is 23
  toggle_inventory.24:
    default: false
    description: max amounts of inventories is 24
  toggle_inventory.25:
    default: false
    description: max amounts of inventories is 25
  toggle_inventory.26:
    default: false
    description: max amounts of inventories is 26
  toggle_inventory.27:
    default: false
    description: max amounts of inventories is 27
  toggle_inventory.28:
    default: false
    description: max amounts of inventories is 28
  toggle_inventory.29:
    default: false
    description: max amounts of inventories is 29
  toggle_inventory.30:
    default: false
    description: max amounts of inventories is 30
