name: moreutils
main: org.moreutils.MoreUtils
version: 1.0
api-version: 1.17
softdepend: [kotlin-stdlib]
commands:
  hp:
    description: show hp
  mu:
    description: moreutils basicuse
  toegg:
    description: open amazing egg
